[package]
name = "first_rust"
version = "0.1.0"
authors = ["Samin Khan <samin9119@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.67"
yew = "0.17.3"

[dependencies.web-sys]
version = "0.3.4"
features = ["Window", "Performance"]
